### PR TITLE
Change buildsystem to build libfuse

### PR DESCRIPTION
**Pull request by purejava**
Fixes `Error: module libfuse: Can't find autogen, autogen.sh or bootstrap` on Cryptomator build.

### CODE REVIEW

**Comment by purejava** [comment]
Fixes https://github.com/flathub/org.cryptomator.Cryptomator/pull/22.

**Comment by infeo** [comment]
For documentation:
The `x-checked-data` property is used by the flatpak plugin [`external data checker`](https://github.com/flathub/flatpak-external-data-checker/pkgs/container/flatpak-external-data-checker#url-checker)

@purejava Why  is `umount-wrapper.sh` added to the the build?

**Comment by purejava** [comment]
> @purejava Why is `umount-wrapper.sh` added to the the build?

For no specific reason. I found the answer on how to build newest libfuse [here](https://github.com/flathub/org.gnome.World.PikaBackup) and they do have the `umount-wrapper.sh`.
Today, I looked at the `LinuxMounter.java` code in the fuse-nio-adapter and it has `"fusermount", "-u"` to unmount, not `umount`.

And: `fusermount3` (how the command is named in libfuse3) [still has](https://man7.org/linux/man-pages/man1/fusermount3.1.html) the `"-u"` parameter. So I think the `umount-wrapper.sh` can be ommited.

**Comment by infeo** [comment]
For Documentation: Build flags for libfuse are found in https://github.com/libfuse/libfuse/blob/fuse-3.13.0/meson_options.txt

**Review by infeo — APPROVED** [review]

**Comment by infeo** [comment]
Thanks again, @purejava for the prompt analysis, resarch and fix!

**Comment by purejava** [comment]
My pleasure @infeo. You are very welcome.

**Pull request merged**
